create_clock -name CLK -period 20.000 [get_ports {CLK}]
create_clock -name ADC_DCLKA -period 20.000 [get_ports {ADC_DCLKA}]
create_clock -name ADC_CLK -period 20.000 [get_ports {ADC_CLK}]
set_clock_latency -source 5 [get_clocks *]
create_clock -name PLL_CLK0 -period 6.666 [get_pins {Corr_Main_1|corr_buffer_update|clk}]
create_clock -name PLL_CLK1 -period 6.666 [get_pins {Corr_Main_1|corr_buffer_update|datain}]
create_clock -name PLL_CLK2 -period 6.666 [get_pins {Corr_Main_1|corr_buffer_update|regout}]
create_clock -name CORR_BUFFER_UPDATE_CLK0 -period 6.666 [get_pins {Corr_Main_1|corr_buffer_update~clkctrl|outclk}]
create_clock -name MRAM_WRITE_DATA_CLK1 -period 100.000 [get_pins {this_read_adc_manager|MRAM_WRITE_DATA|sclr}]
create_clock -name MRAM_WRITE_DATA_CLK2 -period 100.000 [get_pins {this_read_adc_manager|MRAM_WRITE_DATA|clk}]
create_clock -name MRAM_WRITE_DATA_CLK3 -period 100.000 [get_pins {this_read_adc_manager|MRAM_WRITE_DATA|datain}]
create_clock -name MRAM_WRITE_DATA_CLK4 -period 100.000 [get_pins {this_read_adc_manager|MRAM_WRITE_DATA|regout}]