create_clock -name CLK -period 20.000 [get_ports {CLK}]
create_clock -name ADC_DCLKA -period 20.000 [get_ports {ADC_DCLKA}]
create_clock -name ADC_CLK -period 20.000 [get_ports {ADC_CLK}]
set_clock_latency -source 5 [get_clocks *]
create_clock -name PLL_CLK -period 6.666 [get_pins {Corr_Main_1|corr_buffer_update|clk Corr_Main_1|corr_buffer_update|datain Corr_Main_1|corr_buffer_update|regout Corr_Main_1|corr_buffer_update~clkctrl|inclk[0] Corr_Main_1|corr_buffer_update~clkctrl|outclk Corr_Main_1|corr_buffer_update~feeder|combout Corr_Main_1|corr_buffer_update~feeder|datad}]